# Generated by Django 4.2.30 on 2026-09-23 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.SlugField(max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "sucursales",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "todas_las_sucursales",
                    models.BooleanField(
                        default=False,
                        help_text="Sees every branch (e.g. Director, Administrador general).",
                    ),
                ),
                (
                    "sucursales",
                    models.ManyToManyField(
                        blank=True, related_name="usuarios", to="cuentas.sucursal"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("ver_reportes", "Puede ver reportes"),
                    ("generar_reportes", "Puede generar reportes"),
                    ("gestionar_envios", "Puede gestionar envios programados"),
                    ("gestionar_usuarios", "Puede gestionar usuarios y perfiles"),
                ],
            },
        ),
    ]
