# Generated by Django 4.2.30 on 2026-09-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="odoo_company_id",
            field=models.IntegerField(
                blank=True,
                help_text="Odoo res.company id (also ControlPresupuestos_AP's key).",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="wansoft_subsidiary_id",
            field=models.IntegerField(
                blank=True,
                help_text="getglobalcashclosing.subsidiary_id (Wansoft).",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="wansoft_ticket_nombre",
            field=models.CharField(
                blank=True,
                help_text="Sucursal name in getallordenesbyday_* (blank = no ticket detail).",
                max_length=120,
            ),
        ),
    ]
