# Generated by Django 4.2.30 on 2026-10-05 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cuentas", "0002_sucursal_odoo_company_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="correos_reporte",
            field=models.TextField(
                blank=True,
                help_text="Correos fuera del sistema que reciben sus reportes, uno por renglón.",
                verbose_name="correos externos",
            ),
        ),
        migrations.AddField(
            model_name="sucursal",
            name="destinatarios",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios que reciben por defecto los reportes de esta sucursal.",
                related_name="sucursales_destino",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
