# Generated by Django 4.2.30 on 2026-10-05 18:30

from django.db import migrations, models


def metepec_sin_costo(apps, schema_editor):
    # Owner, 2026-10-05: Metepec's cost is not taken into account (Wansoft has had
    # cost pending to discount every month for 22 months).
    apps.get_model("cuentas", "Sucursal").objects.filter(clave="metepec").update(considerar_costo=False)


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_destinatarios_sucursal"),
    ]

    operations = [
        migrations.AddField(
            model_name="sucursal",
            name="considerar_costo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarcado: su reporte sale sin costos y el consolidado no considera su costo.",
            ),
        ),
        migrations.RunPython(metepec_sin_costo, migrations.RunPython.noop),
    ]
