# Generated by Django 4.2.30 on 2026-09-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave",
                    models.SlugField(
                        help_text="Stable technical key; never reuse.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("comercial", "Comercial"),
                            ("operativo", "Operativo"),
                            ("financiero", "Financiero"),
                            ("compras", "Compras"),
                            ("inversionistas", "Inversionistas"),
                            ("ejecutivo", "Ejecutivo"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                            ("semestral", "Semestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "plantilla",
                    models.CharField(
                        choices=[
                            ("ejecutiva", "Ejecutiva (plantilla estandar Fonda)"),
                            ("financiera", "Informe financiero (plantilla nueva)"),
                            ("tabular", "Tabular / Excel"),
                            ("semaforos", "Tabla con semaforos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuente",
                    models.CharField(
                        choices=[
                            ("odoo", "Odoo"),
                            ("mysql_prod", "MySQL productivo (Wansoft)"),
                            ("mixta", "Mixta (Odoo + MySQL + Presupuestos AP)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alcance",
                    models.CharField(
                        choices=[
                            ("por_sucursal", "Un reporte por sucursal"),
                            (
                                "consolidado",
                                "Consolidado (todas las sucursales juntas)",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("admite_pdf", models.BooleanField(default=False)),
                ("admite_excel", models.BooleanField(default=False)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente_definicion", "Pendiente de definir"),
                            ("definido", "Definido (aun sin generador en la web)"),
                            ("implementado", "Implementado"),
                        ],
                        default="pendiente_definicion",
                        max_length=24,
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True, help_text="Open questions / definition notes."
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "perfiles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Profiles allowed to see this report. Empty = nobody (except staff).",
                        related_name="reportes",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "reportes",
                "ordering": ["categoria", "nombre"],
            },
        ),
    ]
