# Generated by Django 4.2.30 on 2026-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="alcance",
            field=models.CharField(
                choices=[
                    ("por_sucursal", "Un reporte por sucursal"),
                    ("consolidado", "Consolidado (todas las sucursales juntas)"),
                    ("ambos", "Por sucursal y consolidado"),
                ],
                max_length=20,
            ),
        ),
    ]
