# Generated by Django 4.2.30 on 2026-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0002_alter_reporte_alcance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("comercial", "Comercial"),
                    ("operativo", "Operativo"),
                    ("financiero", "Financiero"),
                    ("compras", "Compras"),
                    ("inversionistas", "Inversionistas"),
                    ("ejecutivo", "Ejecutivo"),
                    ("nomina", "Nómina / RH"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="fuente",
            field=models.CharField(
                choices=[
                    ("odoo", "Odoo"),
                    ("mysql_prod", "MySQL productivo (Wansoft)"),
                    ("mixta", "Mixta (Odoo + MySQL + Presupuestos AP)"),
                    ("buk", "Buk (nómina, API)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="periodicidad",
            field=models.CharField(
                choices=[
                    ("diaria", "Diaria"),
                    ("semanal", "Semanal"),
                    ("quincenal", "Quincenal"),
                    ("mensual", "Mensual"),
                    ("semestral", "Semestral"),
                    ("anual", "Anual"),
                ],
                max_length=20,
            ),
        ),
    ]
