# Generated by Django 4.2.30 on 2026-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0003_alter_reporte_categoria_alter_reporte_fuente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("comercial", "Comercial"),
                    ("operativo", "Operativo"),
                    ("financiero", "Financiero"),
                    ("compras", "Compras"),
                    ("inversionistas", "Inversionistas"),
                    ("ejecutivo", "Ejecutivo"),
                    ("nomina", "Nómina / RH"),
                    ("sucursales", "Sucursales (gerentes)"),
                    ("cedis", "CEDIS (Bodegón)"),
                    ("contabilidad", "Contabilidad"),
                    ("inventarios", "Inventarios"),
                    ("socios", "Socios"),
                ],
                max_length=20,
            ),
        ),
    ]
