# Generated by Django 4.2.30 on 2026-09-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0006_operativo_a_sucursales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("marca", "Marca"),
                    ("sucursales", "Sucursales (gerentes)"),
                    ("inversionistas", "Inversionistas"),
                    ("cedis", "CEDIS (Bodegón)"),
                    ("nomina", "Nómina / RH"),
                    ("contabilidad", "Contabilidad"),
                    ("inventarios", "Inventarios"),
                    ("compras", "Compras"),
                ],
                max_length=20,
            ),
        ),
    ]
