# Generated by Django 4.2.30 on 2026-09-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_sucursal_odoo_company_id_and_more"),
        ("central", "0008_sin_categoria_compras"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteCedis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "odoo_partner_id",
                    models.IntegerField(
                        help_text="res.partner id in Odoo (customer or delivery address).",
                        unique=True,
                    ),
                ),
                (
                    "nombre_odoo",
                    models.CharField(
                        help_text="Name in Odoo, for reference.", max_length=200
                    ),
                ),
                (
                    "etiqueta",
                    models.CharField(
                        blank=True,
                        help_text="Name to show when it is not one of our branches (e.g. Perisur, León).",
                        max_length=80,
                    ),
                ),
                (
                    "excluir",
                    models.BooleanField(
                        default=False,
                        help_text="Left out of the reports (e.g. Público general, CEDIS to CEDIS).",
                    ),
                ),
                (
                    "nota",
                    models.CharField(
                        blank=True,
                        help_text="Shown in the report's notes (e.g. internal delivery).",
                        max_length=200,
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clientes_cedis",
                        to="cuentas.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente de CEDIS (Odoo)",
                "verbose_name_plural": "clientes de CEDIS (Odoo)",
                "ordering": ["nombre_odoo"],
            },
        ),
    ]
