# Generated by Django 4.2.30 on 2026-10-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cuentas", "0002_sucursal_odoo_company_id_and_more"),
        ("central", "0009_clientes_cedis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automatizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("activa", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("semana", "Semanal"),
                            ("mes", "Mensual"),
                            ("bimestre", "Bimestral"),
                            ("trimestre", "Trimestral"),
                            ("semestre", "Semestral"),
                            ("anio", "Anual"),
                        ],
                        default="semana",
                        max_length=12,
                        verbose_name="frecuencia",
                    ),
                ),
                (
                    "dias_despues",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 = el día siguiente al cierre (lunes para una semana, día 1 para un mes).",
                        verbose_name="días después del cierre",
                    ),
                ),
                ("hora", models.TimeField(default="08:00")),
                (
                    "todas_las_sucursales",
                    models.BooleanField(
                        default=True,
                        help_text="Todas las sucursales activas, también las que se abran después.",
                    ),
                ),
                ("enviar_consolidado", models.BooleanField(default=False)),
                (
                    "enviar_particulares",
                    models.BooleanField(
                        default=True, verbose_name="enviar uno por sucursal"
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("ambos", "PDF y Excel"),
                        ],
                        default="pdf",
                        max_length=8,
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Reglas del reporte, p. ej. incluir_costos.",
                    ),
                ),
                (
                    "correos_extra",
                    models.TextField(
                        blank=True,
                        help_text="Correos fuera del sistema, uno por renglón.",
                    ),
                ),
                (
                    "gerente_su_sucursal",
                    models.BooleanField(
                        default=True,
                        help_text="Los reportes por sucursal le llegan a cada destinatario solo de las sucursales de su perfil.",
                        verbose_name="a cada quien solo su sucursal",
                    ),
                ),
                ("creada", models.DateTimeField(auto_now_add=True)),
                ("actualizada", models.DateTimeField(auto_now=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destinatarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automatizaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automatizaciones",
                        to="central.reporte",
                    ),
                ),
                (
                    "sucursales",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automatizaciones",
                        to="cuentas.sucursal",
                    ),
                ),
            ],
            options={
                "verbose_name": "automatización",
                "verbose_name_plural": "automatizaciones",
                "ordering": ["reporte", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="EnvioAutomatico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                ("programado_para", models.DateTimeField()),
                ("enviado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("enviado", "Enviado"),
                            ("error", "Error"),
                            ("sin_destinatarios", "Sin destinatarios"),
                        ],
                        max_length=20,
                    ),
                ),
                ("destinatarios", models.TextField(blank=True)),
                ("archivos", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("intentos", models.PositiveSmallIntegerField(default=0)),
                (
                    "automatizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="central.automatizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "envío automático",
                "verbose_name_plural": "envíos automáticos",
                "ordering": ["-programado_para"],
            },
        ),
        migrations.AddConstraint(
            model_name="envioautomatico",
            constraint=models.UniqueConstraint(
                fields=("automatizacion", "desde"), name="un_envio_por_periodo"
            ),
        ),
    ]
