# Generated by Django 4.2.30 on 2026-10-05 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("central", "0010_automatizaciones"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automatizacion",
            name="correos_extra",
        ),
        migrations.RemoveField(
            model_name="automatizacion",
            name="destinatarios",
        ),
        migrations.RemoveField(
            model_name="automatizacion",
            name="gerente_su_sucursal",
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="consolidado_correos",
            field=models.TextField(
                blank=True, help_text="Correos fuera del sistema, uno por renglón."
            ),
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="consolidado_destinatarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="automatizaciones_consolidado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="particulares_a_sucursal",
            field=models.BooleanField(
                default=True,
                help_text="Cada sucursal recibe solo su reporte (destinatarios definidos en la sucursal).",
                verbose_name="a los destinatarios de cada sucursal",
            ),
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="particulares_correos",
            field=models.TextField(
                blank=True, help_text="Correos fuera del sistema, uno por renglón."
            ),
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="particulares_destinatarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="automatizaciones_particulares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automatizacion",
            name="particulares_solo_sus_sucursales",
            field=models.BooleanField(
                default=True,
                help_text="Los usuarios agregados reciben solo las sucursales de su perfil; los correos externos, todas.",
                verbose_name="cada quien solo sus sucursales",
            ),
        ),
    ]
