# Generated by Django 4.2.30 on 2026-10-06 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("central", "0011_destinatarios_separados"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvioManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(max_length=120)),
                ("desde", models.DateField()),
                ("hasta", models.DateField()),
                ("destinatarios", models.TextField()),
                ("archivos", models.TextField(blank=True)),
                ("mensaje", models.TextField(blank=True)),
                ("enviado_en", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField(blank=True)),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios_manuales",
                        to="central.reporte",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "envío manual",
                "verbose_name_plural": "envíos manuales",
                "ordering": ["-enviado_en"],
            },
        ),
    ]
