# Generated by Django 4.2.30 on 2026-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0012_envios_manuales"),
    ]

    operations = [
        migrations.AddField(
            model_name="enviomanual",
            name="parametros",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
