# Generated by Django 4.2.30 on 2026-10-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("central", "0013_envio_manual_parametros"),
    ]

    operations = [
        migrations.AddField(
            model_name="automatizacion",
            name="titulo",
            field=models.CharField(
                blank=True,
                help_text="Cómo se llama el reporte en el asunto y el texto del correo (vacío: el nombre del reporte). El periodo se agrega solo.",
                max_length=150,
                verbose_name="título en el correo",
            ),
        ),
    ]
